name: deploy-msix-release

on:
  workflow_dispatch:

jobs:
  deploy-github-release:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      GITHUB_USERNAME: ${{ github.repository_owner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Build .NET
        run: dotnet build

      - name: Decode and save certificate
        run: |
          $certBytes = [Convert]::FromBase64String("${{ secrets.CODE_SIGNING_CERTIFICATE }}")
          $certPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "AiToys.pfx"
          [IO.File]::WriteAllBytes($certPath, $certBytes)
          echo "CERTIFICATE_PATH=$certPath" | Out-File -FilePath $env:GITHUB_ENV -Append
          $certPassword = ConvertTo-SecureString -String ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }} -Force -AsPlainText
          Import-PfxCertificate -FilePath $certPath -CertStoreLocation Cert:\CurrentUser\My -Password $certPassword
        shell: pwsh

      - name: Build MSIX
        run: |
          dotnet build .\src\AiToys\AiToys.csproj `
            /p:Configuration=Release `
            /p:RuntimeIdentifier=win-x64 `
            /p:Platform=x64 `
            /p:PackageCertificateKeyFile=$env:CERTIFICATE_PATH `
            /p:PackageCertificateThumbprint=${{ secrets.CODE_SIGNING_CERTIFICATE_THUMBPRINT }}

        shell: pwsh

      - name: Prepare publish directory
        run: |
          New-Item -ItemType Directory -Force -Path ".\publish"
          Copy-Item -Path ".\msix\AppPackages\*\*.msix" -Destination ".\publish"
          Copy-Item -Path ".\msix\cert\*.cer" -Destination ".\publish"
          Copy-Item -Path ".\msix\scripts\*.ps1" -Destination ".\publish"
          Copy-Item -Path ".\msix\scripts\README.md" -Destination ".\publish"

      - name: Zip MSIX
        run: |
          New-Item -ItemType Directory -Force -Path ".\release"
          Compress-Archive -Path ".\publish\*" -DestinationPath ".\release\ai-toys-msix.zip"
        shell: pwsh

      - name: Deploy GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          token: ${{ secrets.REPOSITORY_TOKEN }}
          body_path: CHANGELOG.md
