name: deploy-github-release

on:
  workflow_dispatch:

jobs:
  deploy-github-release:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      GITHUB_USERNAME: ${{ github.repository_owner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Create EXE
        run: |
          dotnet publish src/AiToys/AiToys.csproj `
            /p:Configuration=Release `
            /p:RuntimeIdentifier=win-x64 `
            /p:Platform=x64 `
            /p:WindowsPackageType=None `
            /p:AppxPackageSigningEnabled=false `
            /p:GenerateAppxPackageOnBuild=false
        shell: pwsh

      - name: Zip EXE
        run: |
          New-Item -Path "release" -ItemType Directory -Force
          Compress-Archive -Path "publish/*" -DestinationPath "release/ai-toys-exe.zip" -Force
        shell: pwsh

      - name: Deploy GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          token: ${{ secrets.REPOSITORY_TOKEN }}
          body_path: CHANGELOG.md
